server:
  port: 7750
application:
  dataBase: sqlBase
  dataBase.filePath.base: devBase.txt
  dataBase.filePath.invoiceId: devBaseId.txt
logging:
  file:
    name: Logs/devLogs.log
  level:
    pl:
      futurecollars:
        invoicing: INFO
        db: DEBUG
spring:
  output:
    ansi:
      enabled: always

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/invoicing
    username: postgres
    password: Piotr
    driver-class-name: org.postgresql.Driver
  flyway:
     enabled: true
