server:
  port: 5555
application:
  dataBase: fileBase
  dataBase.filePath.base: prodBase.txt
  dataBase.filePath.invoiceId: prodBaseId.txt
  logging:
    file:
      name: Logs/prodLogs.log
    level:
      pl:
        futurecollars:
          invoicing: INFO
          db: DEBUG
spring:
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicing
    username: postgres
    password: Piotr
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false