package pl.futurecollars.invoicing.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@AllArgsConstructor
@NoArgsConstructor
@Data
@Builder
public class InvoiceEntry {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @JsonIgnore
  @ApiModelProperty(value = "Invoice entry id (generated by application)", required = true, example = "1")
  private Long id;
  @ApiModelProperty(value = "Product/service description", required = true, example = " toner/cleaning windows")
  private String description;
  @ApiModelProperty(value = "products quantity", required = true, example = "1")
  private BigDecimal quantity;
  @ApiModelProperty(value = "Price value", required = true, example = " 20", dataType = "BigDecimal")
  private BigDecimal price;
  @ApiModelProperty(value = "vat value", required = true, example = " 23")
  private BigDecimal vatValue;
  @Enumerated(EnumType.STRING)
  @ApiModelProperty(value = "Vat tax rate", required = true)
  private Vat vatRate;
  @OneToOne(cascade = CascadeType.ALL)
  @JoinColumn(name = "expanse_for_car")
  @ApiModelProperty(value = "car data", required = true)
  private Car expansForCar;


}
