name: CI

on:
  push:
    branches: [Lesson*]
  pull_request:
    branches: [Lesson*]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          cache: 'gradle'
      - name: Build with gradle
        run: ./gradlew build
